site_name: Cloud Services - Lab Tasks
site_description: Academic lab tasks and exercises for cloud services from AWS, Azure, and other cloud vendors
site_url: https://dipaish.github.io/cloudServices/
repo_url: https://github.com/dipaish/cloudServices
theme:
  name: dracula
  logo: ddd.png
  favicon: ddd.png

extra_css:
  - stylesheets/custom.css

extra_javascript:
  - javascripts/copy-code.js
  - javascripts/footer.js
  - javascripts/nav-style.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dipaish
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kcdeepak112/
      name: LinkedIn

nav:
  - Home: index.md
  - AWS Fundamentals:
    - WordPress Guide: awsfundamentals/wpGuide.md
    - EC2 Instance: awsfundamentals/ec2Instance_session1.md
    - Database Server: awsfundamentals/databaseServer.md
    - AWS Lambda: awsfundamentals/aws_lambda.md
    - Elastic Beanstalk: awsfundamentals/beanstalk.md
    - Project Work: awsfundamentals/projectWork_pilviPalvelut.md
  - AWS Developer Labs:
      - Developer Lab 1: developerLab1.md
      - Developer Lab 2: developerLab2.md
      - Developer Lab 3: developerLab3.md
  - AWS Architect Labs:
      - Architect Lab 1: architect/architectLab1.md
      - Architect Lab 2: architect/architectLab2.md
  - Linux Command Guide: linux/linux1.md

markdown_extensions:
  - admonition
  - md_in_html
  - toc:
      permalink: true
  - tables
