site_name: Cloud Services - Lab Tasks
site_description: Academic lab tasks and exercises for cloud services from AWS, Azure, and other cloud vendors
site_url: https://dipaish.github.io/cloudServices/
repo_url: https://github.com/dipaish/cloudServices
theme:
  name: dracula
  logo: ddd.png
  favicon: ddd.png

extra_css:
  - stylesheets/custom.css

extra_javascript:
  - javascripts/copy-code.js
  - javascripts/footer.js
  - javascripts/nav-style.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dipaish
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kcdeepak112/
      name: LinkedIn

nav:
  - Home: index.md
  - Lab Tasks:
      - Cloud Developer:
          - AWS: part1.md

markdown_extensions:
  - admonition
  - md_in_html
  - toc:
      permalink: true
  - tables
